# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_ekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(991, 487)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.521368 rgba(28, 29, 73, 255));border-radius: 30px;")
        self.arka_ekran = QtWidgets.QLabel(Dialog)
        self.arka_ekran.setGeometry(QtCore.QRect(0, 0, 1000, 491))
        self.arka_ekran.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.521368 rgba(28, 29, 73, 255));\n"
"border-radius: 30px;")
        self.arka_ekran.setText("")
        self.arka_ekran.setObjectName("arka_ekran")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(50, 60, 900, 400))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 400))
        self.stackedWidget.setStyleSheet("background-color: rgb(60, 231, 195,150);\n"
"border-radius: 12px;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(60, 231, 195,150);\n"
"")
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 141, 16))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"image:none;\n"
"border-radius: 5px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_3.setStyleSheet("border-radius: 5px;\n"
"image:none;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 141, 16))
        self.label_5.setStyleSheet("border-radius: 5px;\n"
"image:none;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(20, 290, 131, 16))
        self.label_6.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 141, 16))
        self.label_7.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 141, 16))
        self.label_8.setStyleSheet("image:none;font: 10pt \"MS Shell Dlg 2\";border-radius: 5px;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(20, 350, 131, 16))
        self.label_9.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 131, 16))
        self.label_4.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 131, 16))
        self.label_12.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(20, 200, 141, 16))
        self.label_10.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.kurtarma_d = QtWidgets.QLabel(self.page)
        self.kurtarma_d.setGeometry(QtCore.QRect(180, 200, 80, 16))
        self.kurtarma_d.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.kurtarma_d.setObjectName("kurtarma_d")
        self.R_gps_uydu = QtWidgets.QLabel(self.page)
        self.R_gps_uydu.setGeometry(QtCore.QRect(180, 180, 80, 16))
        self.R_gps_uydu.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.R_gps_uydu.setObjectName("R_gps_uydu")
        self.P_gps_irtifa = QtWidgets.QLineEdit(self.page)
        self.P_gps_irtifa.setGeometry(QtCore.QRect(180, 290, 80, 16))
        self.P_gps_irtifa.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.P_gps_irtifa.setObjectName("P_gps_irtifa")
        self.P_gps_enlem = QtWidgets.QLineEdit(self.page)
        self.P_gps_enlem.setGeometry(QtCore.QRect(180, 310, 80, 16))
        self.P_gps_enlem.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.P_gps_enlem.setObjectName("P_gps_enlem")
        self.P_gps_boylam = QtWidgets.QLineEdit(self.page)
        self.P_gps_boylam.setGeometry(QtCore.QRect(180, 330, 80, 16))
        self.P_gps_boylam.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.P_gps_boylam.setObjectName("P_gps_boylam")
        self.P_gps_uydu = QtWidgets.QLineEdit(self.page)
        self.P_gps_uydu.setGeometry(QtCore.QRect(180, 350, 80, 16))
        self.P_gps_uydu.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.P_gps_uydu.setObjectName("P_gps_uydu")
        self.R_boylam = QtWidgets.QLineEdit(self.page)
        self.R_boylam.setGeometry(QtCore.QRect(180, 160, 80, 16))
        self.R_boylam.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.R_boylam.setObjectName("R_boylam")
        self.R_irtifa = QtWidgets.QLineEdit(self.page)
        self.R_irtifa.setGeometry(QtCore.QRect(180, 100, 80, 16))
        self.R_irtifa.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.R_irtifa.setObjectName("R_irtifa")
        self.R_gps_irtifa = QtWidgets.QLineEdit(self.page)
        self.R_gps_irtifa.setGeometry(QtCore.QRect(180, 120, 80, 16))
        self.R_gps_irtifa.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";")
        self.R_gps_irtifa.setObjectName("R_gps_irtifa")
        self.R_enlem = QtWidgets.QLineEdit(self.page)
        self.R_enlem.setGeometry(QtCore.QRect(180, 140, 80, 16))
        self.R_enlem.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";")
        self.R_enlem.setObjectName("R_enlem")
        self.Roket_Map = QtWidgets.QWidget(self.page)
        self.Roket_Map.setGeometry(QtCore.QRect(640, 20, 230, 200))
        self.Roket_Map.setObjectName("Roket_Map")
        self.map_payload = QtWidgets.QLabel(self.Roket_Map)
        self.map_payload.setGeometry(QtCore.QRect(0, 0, 220, 200))
        self.map_payload.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"image:none;")
        self.map_payload.setObjectName("map_payload")
        self.Payload_Map = QtWidgets.QWidget(self.page)
        self.Payload_Map.setGeometry(QtCore.QRect(360, 20, 230, 200))
        self.Payload_Map.setObjectName("Payload_Map")
        self.map_roket = QtWidgets.QLabel(self.Payload_Map)
        self.map_roket.setGeometry(QtCore.QRect(0, 0, 220, 200))
        self.map_roket.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);\n"
"image:none;")
        self.map_roket.setObjectName("map_roket")
        self.hyi_baglan = QtWidgets.QPushButton(self.page)
        self.hyi_baglan.setGeometry(QtCore.QRect(510, 360, 75, 23))
        self.hyi_baglan.setStyleSheet("QPushButton {\n"
"    color:rgb(250,250,250);\n"
"    border: none;\n"
"    border-radius: 10px;        \n"
"    background-color:  rgb(0, 85, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(0, 85, 127, 100);\n"
"}")
        self.hyi_baglan.setObjectName("hyi_baglan")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 280, 161, 23))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font: 20pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 3px;        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 255, 255 150);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.hyi_combox = QtWidgets.QComboBox(self.page)
        self.hyi_combox.setGeometry(QtCore.QRect(510, 310, 160, 25))
        self.hyi_combox.setStyleSheet("color:rgb(250,250,250);\n"
"border: none;\n"
"border-radius: 10px;        \n"
"background-color: rgb(0, 85, 127);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.hyi_combox.setObjectName("hyi_combox")
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(695, 280, 180, 23))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    border-radius: 3px;        \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 255, 255 150);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.yer_combox = QtWidgets.QComboBox(self.page)
        self.yer_combox.setGeometry(QtCore.QRect(695, 310, 180, 25))
        self.yer_combox.setStyleSheet("color:rgb(250,250,250);\n"
"border: none;\n"
"border-radius: 10px;        \n"
"background-color: rgb(0, 85, 127);\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.yer_combox.setObjectName("yer_combox")
        self.yer_istasyon_baglan = QtWidgets.QPushButton(self.page)
        self.yer_istasyon_baglan.setGeometry(QtCore.QRect(695, 360, 75, 23))
        self.yer_istasyon_baglan.setStyleSheet("QPushButton {\n"
"    color:rgb(250,250,250);\n"
"    border: none;\n"
"    border-radius: 10px;        \n"
"    background-color:  rgb(0, 85, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(0, 85, 127, 100);\n"
"}")
        self.yer_istasyon_baglan.setObjectName("yer_istasyon_baglan")
        self.yer_istasyon_kes = QtWidgets.QPushButton(self.page)
        self.yer_istasyon_kes.setGeometry(QtCore.QRect(800, 360, 75, 23))
        self.yer_istasyon_kes.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color:rgb(250,250,250);\n"
"\n"
"    border-radius: 10px;        \n"
"    background-color: rgb(0, 85, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(0, 85, 127, 150);\n"
"}")
        self.yer_istasyon_kes.setObjectName("yer_istasyon_kes")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(20, 220, 141, 16))
        self.label_13.setStyleSheet("image:none;font: 10pt \"MS Shell Dlg 2\";border-radius: 5px;\n"
"")
        self.label_13.setObjectName("label_13")
        self.R_x_v = QtWidgets.QLineEdit(self.page)
        self.R_x_v.setGeometry(QtCore.QRect(180, 220, 80, 16))
        self.R_x_v.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.R_x_v.setObjectName("R_x_v")
        self.R_y_v = QtWidgets.QLabel(self.page)
        self.R_y_v.setGeometry(QtCore.QRect(180, 240, 80, 16))
        self.R_y_v.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.R_y_v.setObjectName("R_y_v")
        self.label_20 = QtWidgets.QLabel(self.page)
        self.label_20.setGeometry(QtCore.QRect(20, 260, 141, 16))
        self.label_20.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.R_z_v = QtWidgets.QLabel(self.page)
        self.R_z_v.setGeometry(QtCore.QRect(180, 260, 80, 16))
        self.R_z_v.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.R_z_v.setObjectName("R_z_v")
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setGeometry(QtCore.QRect(20, 240, 141, 16))
        self.label_24.setStyleSheet("border-radius: 5px;image:none;font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.sayac = QtWidgets.QLineEdit(self.page)
        self.sayac.setGeometry(QtCore.QRect(180, 80, 80, 16))
        self.sayac.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.sayac.setObjectName("sayac")
        self.label_25 = QtWidgets.QLabel(self.page)
        self.label_25.setGeometry(QtCore.QRect(20, 80, 141, 16))
        self.label_25.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"image:none;\n"
"border-radius: 5px;\n"
"")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page)
        self.label_26.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.label_26.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"image:none;\n"
"border-radius: 5px;\n"
"")
        self.label_26.setObjectName("label_26")
        self.t_id = QtWidgets.QLineEdit(self.page)
        self.t_id.setGeometry(QtCore.QRect(180, 60, 80, 16))
        self.t_id.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.t_id.setObjectName("t_id")
        self.label_27 = QtWidgets.QLabel(self.page)
        self.label_27.setGeometry(QtCore.QRect(360, 220, 61, 20))
        self.label_27.setStyleSheet("border-radius: 5px;\n"
"image:none;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.R_toplu_gps = QtWidgets.QLineEdit(self.page)
        self.R_toplu_gps.setGeometry(QtCore.QRect(430, 220, 155, 20))
        self.R_toplu_gps.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";")
        self.R_toplu_gps.setObjectName("R_toplu_gps")
        self.label_29 = QtWidgets.QLabel(self.page)
        self.label_29.setGeometry(QtCore.QRect(640, 220, 61, 20))
        self.label_29.setStyleSheet("border-radius: 5px;\n"
"image:none;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.P_toplu_gps = QtWidgets.QLineEdit(self.page)
        self.P_toplu_gps.setGeometry(QtCore.QRect(710, 220, 155, 20))
        self.P_toplu_gps.setStyleSheet("border-radius: 5px;font: 10pt \"MS Shell Dlg 2\";")
        self.P_toplu_gps.setObjectName("P_toplu_gps")
        self.ekran_degistir_anaekran = QtWidgets.QPushButton(self.page)
        self.ekran_degistir_anaekran.setGeometry(QtCore.QRect(10, 10, 75, 21))
        self.ekran_degistir_anaekran.setObjectName("ekran_degistir_anaekran")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(300, 0, 300, 50))
        self.label_15.setStyleSheet("color:rgb(255, 255, 255);\n"
"image:none;\n"
"background-color: rgb(60, 231, 195,150);\n"
"border-radius: 12px;\n"
"font: 30pt \"MS Shell Dlg 2\";\n"
"")
        self.label_15.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 70, 301, 311))
        self.plainTextEdit.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(620, 343, 271, 20))
        self.label.setStyleSheet("font: 90 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(24, 24, 24);\n"
"border-radius: 10x;\n"
"image:none;\n"
"")
        self.label.setObjectName("label")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(620, 370, 231, 21))
        self.label_17.setStyleSheet("color:rgb(45, 45, 45);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"image:none;\n"
"")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(619, 20, 271, 300))
        self.label_18.setStyleSheet("image: url(:/Roket/Roket.PNG);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(330, 70, 241, 311))
        self.plainTextEdit_2.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.ekran_degistir_bilgi = QtWidgets.QPushButton(self.page_2)
        self.ekran_degistir_bilgi.setGeometry(QtCore.QRect(10, 10, 75, 21))
        self.ekran_degistir_bilgi.setObjectName("ekran_degistir_bilgi")
        self.plainTextEdit.raise_()
        self.label_15.raise_()
        self.label.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.plainTextEdit_2.raise_()
        self.ekran_degistir_bilgi.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.btn_buyut = QtWidgets.QPushButton(Dialog)
        self.btn_buyut.setGeometry(QtCore.QRect(876, 25, 17, 17))
        self.btn_buyut.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_buyut.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_buyut.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;    \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.btn_buyut.setText("")
        self.btn_buyut.setObjectName("btn_buyut")
        self.btn_kucult = QtWidgets.QPushButton(Dialog)
        self.btn_kucult.setGeometry(QtCore.QRect(903, 25, 17, 17))
        self.btn_kucult.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_kucult.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_kucult.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_kucult.setText("")
        self.btn_kucult.setObjectName("btn_kucult")
        self.btn_kapa = QtWidgets.QPushButton(Dialog)
        self.btn_kapa.setGeometry(QtCore.QRect(930, 25, 17, 17))
        self.btn_kapa.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_kapa.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_kapa.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_kapa.setText("")
        self.btn_kapa.setObjectName("btn_kapa")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 61, 41))
        self.label_14.setStyleSheet("image: url(:/lgo_png/magnetar-logo_png.png);\n"
"background-color:none")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Roket İrtifa (m):"))
        self.label_3.setText(_translate("Dialog", "Roket GPS İrtifa (m):"))
        self.label_5.setText(_translate("Dialog", "Roket GPS Enlem:"))
        self.label_6.setText(_translate("Dialog", "Payload GPS İrtifa (m):"))
        self.label_7.setText(_translate("Dialog", "Roket GPS Uydu:"))
        self.label_8.setText(_translate("Dialog", "Roket GPS Boylam:"))
        self.label_9.setText(_translate("Dialog", "Payload GPS Uydu:"))
        self.label_4.setText(_translate("Dialog", "Payload GPS Boylam:"))
        self.label_12.setText(_translate("Dialog", "Patload GPS Enlem:"))
        self.label_10.setText(_translate("Dialog", "Kurtarma Durumu:"))
        self.kurtarma_d.setText(_translate("Dialog", "0"))
        self.R_gps_uydu.setText(_translate("Dialog", "8"))
        self.P_gps_irtifa.setText(_translate("Dialog", "15.8"))
        self.P_gps_enlem.setText(_translate("Dialog", "41.045574"))
        self.P_gps_boylam.setText(_translate("Dialog", "29.034420"))
        self.P_gps_uydu.setText(_translate("Dialog", "7"))
        self.R_boylam.setText(_translate("Dialog", "32.850606"))
        self.R_irtifa.setText(_translate("Dialog", "10.2"))
        self.R_gps_irtifa.setText(_translate("Dialog", "10"))
        self.R_enlem.setText(_translate("Dialog", "39.911590"))
        self.map_payload.setText(_translate("Dialog", "Payload Map"))
        self.map_roket.setText(_translate("Dialog", "Roket Map"))
        self.hyi_baglan.setText(_translate("Dialog", "Bağlan"))
        self.pushButton_3.setText(_translate("Dialog", "HYI"))
        self.pushButton_4.setText(_translate("Dialog", "Yer İstasyonu"))
        self.yer_istasyon_baglan.setText(_translate("Dialog", "Bağlan"))
        self.yer_istasyon_kes.setText(_translate("Dialog", "Kes"))
        self.label_13.setText(_translate("Dialog", "Roket X Eksen Verisi (°): "))
        self.R_x_v.setText(_translate("Dialog", "2"))
        self.R_y_v.setText(_translate("Dialog", "15"))
        self.label_20.setText(_translate("Dialog", "Roket Z Eksen Verisi (°):"))
        self.R_z_v.setText(_translate("Dialog", "-5"))
        self.label_24.setText(_translate("Dialog", "Roket Y Eksen Verisi (°):"))
        self.sayac.setText(_translate("Dialog", "0"))
        self.label_25.setText(_translate("Dialog", "Sayac"))
        self.label_26.setText(_translate("Dialog", "Takım İd:"))
        self.t_id.setText(_translate("Dialog", "253"))
        self.label_27.setText(_translate("Dialog", "Konum:"))
        self.R_toplu_gps.setText(_translate("Dialog", "39.911590,32.850606"))
        self.label_29.setText(_translate("Dialog", "Konum:"))
        self.P_toplu_gps.setText(_translate("Dialog", "39.911590,32.850606"))
        self.ekran_degistir_anaekran.setText(_translate("Dialog", "←→"))
        self.label_15.setText(_translate("Dialog", "Biz Kimiz ? "))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Okulumuzdaki bir grup lise öğrencisi tarafından Teknofest Roket Yarışması\'nda mücadele etmek üzere kuru lan Magnetar Roket Takımı, toplamda 7 +1 Danışman Öğretmenden   oluşmak tadır. Magnetar, henüz bir roket takımı olarak faal iyetlerini sürdürmek ile beraber geleceğe yönelik hedeflere de sahiptir. Bu he deflerden birisi de uzay bil imleri ve yenilikçi teknolo jiler alanında çalışmalar yaparak, ülkenin bu alanlar da gelişmesine katkı sağlam aktır."))
        self.label.setText(_translate("Dialog", "Program ve Diğer Yazılımların Sahibi"))
        self.label_17.setText(_translate("Dialog", "Fahrihan Şahin - sahinfahrihan0"))
        self.plainTextEdit_2.setPlainText(_translate("Dialog", "Danışman Öğretmen,\n"
"\"İbrahim ÇALIŞKAN\"\n"
"\n"
"Öğrenciler,\n"
"\"Fahrihan ŞAHİN\"\n"
"\"Eyüp Ensar KARAGÖZ\"\n"
"\"Alim AYDOĞDU\"\n"
"\"Muhammed Furkan KARİP\" \"Ahmet Emin YALÇIN\"\n"
"\"Eren Boğaz\"\n"
"\"Ömer Burak GÖZÜAÇIK\"\n"
""))
        self.ekran_degistir_bilgi.setText(_translate("Dialog", "←→"))
        self.btn_buyut.setToolTip(_translate("Dialog", "Maximize"))
        self.btn_kucult.setToolTip(_translate("Dialog", "Minimize"))
        self.btn_kapa.setToolTip(_translate("Dialog", "Close"))
import logo_png_rc
import magnetar_yazi_rc
import roket_grc_rc
